version: '3.6'

services:
  url-db:
    container_name: url-db
    build:
      context: ./services/server/db
      dockerfile: Dockerfile
    ports:
      - 27018:27017
    volumes:
      - ./services/server/db/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
