version: '3.6'

services:
  mongodb:
    image: mongodb
    container_name: url-shortener-mongodb
    volumes:
      - ./docker/data/db:/data/db
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
